name: Deploy

on:
  push:
    branches:
      - main

permissions: 
  contents: read
  pages: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with: 
          install_command: npm ci
          build_command: npm run build
          path: apps/docs/storybook-static
          checkout: true
